mitos: add tests for R packages (#44971)
* mitos: add tests for R packages

In test with the container I got:

Exception: b"Warning message:\npackage \xe2\x80\x98ggplot2\xe2\x80\x99 was built under R version 3.6.3 \nError: package or namespace load failed for \xe2\x80\x98reshape2\xe2\x80\x99 in dyn.load(file, DLLpath = DLLpath, ...):\n unable to load shared object '/usr/local/lib/R/library/stringi/libs/stringi.so':\n  libicui18n.so.64: cannot open shared object file: No such file or directory\nIn addition: Warning message:\npackage \xe2\x80\x98reshape2\xe2\x80\x99 was built under R version 3.6.3 \nExecution halted\n"

* try to use R directly in tests

* try R > 3

* bump and unpin vienna

* retry R>3

* another try

* try to pin r-stringi

* bump

* cnt

* unpin some more requirements

* remove stringi

* repin infernal

* repin hmmer

* repin blast

* Revert "repin blast"

This reverts commit 6a5717a86f8231c1ced5ca58e21f97f01c264e2f.