Bump kaiju to latest version (#7213)
* Changed url to master from latest version 

Modified url to master from latest release to take advantage of recent changes including gzip compatibility.

* Updated url to reference latest commit 

Modified url from master to latest commit to enable reproducibility

* Change to released version

* Trying to fix OS10 error - Modified fn

* Attempting to fix macOS build error

* Update meta.yaml

* troubleshooting kaiju build on macOS 

added -p per https://github.com/bioinformatics-centre/kaiju/issues/20

* Changed -p to -e

troubleshooting macos build. Linux build is passing. Getting the following error '''File "/tmp/workspace/miniconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/tmp/workspace/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/tmp/workspace/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/tmp/workspace/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/tmp/workspace/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/tmp/workspace/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1147, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/tmp/workspace/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/tmp/workspace/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/tmp/workspace/miniconda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/tmp/workspace/miniconda/conda-bld/kaiju_1517006552538/work/kaiju-1.6.0/conda_build.sh']' returned non-zero exit status 2.'''

* Updating test command as per suggestion from @mbargull

* kaiju: update to 1.6.1

* kaiju: fix no_link entry