Update maker to version 3.01.03
* Remove packages that are not direct dependencies (infernal, mir-prefer)
* File::Which is bundled with MAKER
* MAKER can handle newer tRNAscan output
* Add C compiler to build section to address error:
  d-multi/CORE/perl.h:694:10: fatal error: sys/types.h: No such file or directory