ucsc- bedcommonregions & bedcoverage & bedextendranges & bedgeneparts: add linux-aarch64 build (#48425)
* ucsc- bedcommonregions & bedcoverage & bedextendranges & bedgeneparts: add linux-aarch64 build

Update to v466

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Downgrade bedCoverage and bedExtendRanges to v465

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Revert changes to ucsc-bedextendranges & ucsc-bedcoverage

Their build fails with:
```
12:36:57 ␛[32mBIOCONDA INFO␛[0m (OUT) /usr/local/src/conda/ucsc-bedcoverage-465/kent/src/lib/bamFile.c:257: undefined reference to `cram_set_cache_url'␛[0m
12:36:57 ␛[32mBIOCONDA INFO␛[0m (OUT) /opt/conda/conda-bld/ucsc-bedcoverage_1718195685719/_build_env/bin/../lib/gcc/aarch64-conda-linux-gnu/12.3.0/../../../../aarch64-conda-linux-gnu/bin/ld: /usr/local/src/conda/ucsc-bedcoverage-465/kent/src/lib/bamFile.c:257: undefined reference to `cram_set_cache_url'␛[0m
12:36:57 ␛[32mBIOCONDA INFO␛[0m (OUT) /opt/conda/conda-bld/ucsc-bedcoverage_1718195685719/_build_env/bin/../lib/gcc/aarch64-conda-linux-gnu/12.3.0/../../../../aarch64-conda-linux-gnu/bin/ld: ../../../lib/aarch64/jkweb.a(knetUdc.o): in function `knetUdcInstall':␛[0m
12:36:57 ␛[32mBIOCONDA INFO␛[0m (OUT) /usr/local/src/conda/ucsc-bedcoverage-465/kent/src/lib/knetUdc.c:80: undefined reference to `knet_init_alt'␛[0m
12:36:57 ␛[32mBIOCONDA INFO␛[0m (OUT) /opt/conda/conda-bld/ucsc-bedcoverage_1718195685719/_build_env/bin/../lib/gcc/aarch64-conda-linux-gnu/12.3.0/../../../../aarch64-conda-linux-gnu/bin/ld: /usr/local/src/conda/ucsc-bedcoverage-465/kent/src/lib/knetUdc.c:80: undefined reference to `knet_init_alt'␛[0m
12:36:57 ␛[32mBIOCONDA INFO␛[0m (OUT) collect2: error: ld returned 1 exit status␛[0m
12:36:57 ␛[32mBIOCONDA INFO␛[0m (OUT) make: *** [../../../inc/userApp.mk:31: /opt/conda/conda-bld/ucsc-bedcoverage_1718195685719/work/bin/bedCoverage] Error 1␛[0m
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

---------

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>