[ci skip] Merge PR 22194
Merge PR #22194, commits were: 
 * Update sha256
 * Last change to reqs
 * Try pinning htslib to 1.9
 * samtools 1.9, for htslib 1.9
 * Add all deps and cross fingers
 * Drop python >=3.7 for now
 * Try snakemake-minimal and python >=3.7
 * Try python3 instead of python, to fix snakemake problem
 * Add snakemake req
 * Suggestions from bioconda
 * Drop snakemake dep
 * Not sure of best way to avoid "noarch" error.

    ERROR: recipes/pbipa/meta.yaml:19: should_be_noarch_generic: The
    recipe should be build as "noarch".
 * pbipa-0.0.1