Few potential fixes for bulk  (#62802)
* bump gambit

BIOCONDA ERROR BUILD ERROR: packages with divergent build strings in repository for recipe recipes/gambit. A build number bump is likely needed: ('gambit-1.1.0-py310h1fe012e_2', 'gambit-1.1.0-py311haab0aaa_2', 'gambit-1.1.0-py312h0fa9677_2', 'gambit-1.1.0-py39hbcbf7aa_2')

* bump hictkpy

11:08:08 BIOCONDA ERROR BUILD ERROR: packages with divergent build strings in repository for recipe recipes/hictkpy. A build number bump is likely needed: ('hictkpy-1.4.0-py310hc00559c_0', 'hictkpy-1.4.0-py311hea9d01e_0', 'hictkpy-1.4.0-py312ha9c57b9_0')

* bump genbank

11:09:20 BIOCONDA ERROR BUILD ERROR: packages with divergent build strings in repository for recipe recipes/genbank. A build number bump is likely needed: ('genbank-0.121-py310h1fe012e_1', 'genbank-0.121-py311haab0aaa_1', 'genbank-0.121-py312h0fa9677_1', 'genbank-0.121-py313h366bbf7_1', 'genbank-0.121-py39hbcbf7aa_1')

* ireset build in bioconductor-rbwa

The recipe recipes/bioconductor-rbwa failed linting. See https://bioconda.github.io/contributor/linting.html for details:

ERROR: recipes/bioconductor-rbwa/meta.yaml:16: build_number_needs_reset: The recipe build number should be reset to 0

* Revert "ireset build in bioconductor-rbwa"

This reverts commit a247fbf37d4f472363c633985f3aca2cec3a1d53.