Use at most matplotlib 3.5.x because in newer versions seaborn styles are removed
```
OSError: 'seaborn-ticks' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)␛[0m
2024-12-16T10:02:46.9233988Z 10:02:36 ␛[32mBIOCONDA INFO␛[0m (OUT) WARNING: Tests failed for smcpp-1.15.4-py39hac1eaed_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken␛[0m
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>