[ci skip] Merge PR 19371
Merge PR #19371, commits were: 
 * merged + fixed typo for pyyaml
 * added pyyaml (was previously handled by snakemake)
 * temporarily incactivated snakemake dependency

Creates conflicts with python, which I don't understand since in principle current default python version is 3.8. 
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"python[version='>=2.7,<2.8.0a0']", "python[version='>=3.5.3']"}
 * temporarily inactivated build dependency to python because of version conflicts with snakemake dependency
 * Update meta.yaml
 * added some tests
 * reactivated the compilation of the R package TFBMclust
 * added r-base and python in the build dependencies
 * temporarily commented R compilation because generates error (R: command not found)
 * fixed sha256
 * changed version + added some tests
 * fixed problems with the compilation of C code (was ignored because not in the right directory) + added compilation of the R package TFBMclust
 * commented failing tests
 * Update meta.yaml
 * fixed indentation
 * added some tests

- tests for the compiled C programs
- run random-motif (python program)
- run info-gibbs (compiled C) as sub-command of the rsat command
 * uncommented C programs to be compiled

- count-words 
- matrix-scan-quick 
- retrieve-variation-seq 
- variation-scan
 * changed version to 2019.12.20
 * fixed path for share/rsat/rsat.yaml; added R-files
 * fixed the path $PREFIX/bin/rsat
 * fix sha256
 * fixed inconsistency with sha256
 * added a shebang + suppressed obsolete line + commented most C programs to test a single compilation
 * added DOI and bio.tools ID
 * cleaned obsolete comments in the build file
 * typo + added tests
 * Added LICENSE file
 * shorter summary
 * some lint fixes
 * added rsat-core