sixgill: restrict to py2
as documented in the dev_url (which has been added).
with py3 one runs into errors like

```
2.4-py2.7.egg/EGG-INFO/scripts/sixgill_build", line 112, in main
AttributeError: 'pysam.libcfaidx.FastqFile' object has no attribute 'next'
```