error inside (fixes no. 2, I hope)
ValueError: variant config in /home/vsts/work/1/s/recipes/gimmemotifs/conda_build_config.yaml is ambiguous because it
does not fully implement all zipped keys (To be clear: missing ['numpy', 'python_impl'])
or specifies a subspace that is not fully implemented (To be clear:
.. we did not find ['3.6', '3.7', '3.8', '3.9'] from {'python': ['3.6', '3.7', '3.8', '3.9']} in python:['3.9.*  *_cpython', '3.8.*  *_cpython', '3.7.*  *_cpython', '3.6.*  *_cpython', '2.7.*  *_cpython']).