[ci skip] Merge PR 26517
Merge PR #26517, commits were: 
 * First RepeatMasker process must run exclusively to avoid race condition
 * Add blank line to trigger CircleCI rebuild
 * repsearch package doesn't exist for macos
 * Search for evidence_modeler.pl instead of evm
 * Add evidencemodeler & rapsearch; trim host section
 * Fix should_not_be_noarch_compiler lint error
 * Update maker to version 3.01.03

* Remove packages that are not direct dependencies (infernal, mir-prefer)
* File::Which is bundled with MAKER
* MAKER can handle newer tRNAscan output
* Add C compiler to build section to address error:
  d-multi/CORE/perl.h:694:10: fatal error: sys/types.h: No such file or directory