Append -mno-outline-atomics to CFLAGS
Trying to workaround:
```
 (OUT)     = note: /opt/conda/conda-bld/fastobo_1714466531501/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-9579298f7adeed43.rlib(std-9579298f7adeed43.std.bcf85624a3ea01c2-cgu.0.rcgu.o): in function `std::sys::pal::unix::stack_overflow::imp::sigstack_size':␛[0m
2024-04-30T08:46:25.4562846Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)             /rustc/a8a1d3a771850e1e364eb9010e98789ce758a817/library/std/src/sys/pal/unix/stack_overflow.rs:237: undefined reference to `getauxval'␛[0m
2024-04-30T08:46:25.4563526Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)             /opt/conda/conda-bld/fastobo_1714466531501/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /rustc/a8a1d3a771850e1e364eb9010e98789ce758a817/library/std/src/sys/pal/unix/stack_overflow.rs:237: undefined reference to `getauxval'␛[0m
2024-04-30T08:46:25.4564013Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)             collect2: error: ld returned 1 exit status␛[0m
2024-04-30T08:46:25.4564266Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT) ␛[0m
2024-04-30T08:46:25.4564632Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)     = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified␛[0m
2024-04-30T08:46:25.4565030Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)     = note: use the `-l` flag to specify native libraries to link␛[0m
2024-04-30T08:46:25.4565513Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)     = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)␛[0m
2024-04-30T08:46:25.4565898Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT) ␛[0m
2024-04-30T08:46:25.4566195Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)   error: could not compile `thiserror` (build script) due to 1 previous error␛[0m
2024-04-30T08:46:25.4566496Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT) ␛[0m
2024-04-30T08:46:25.4566716Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)   Caused by:␛[0m
2024-04-30T08:46:36.5574778Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)     process didn't exit successfully: `/home/conda/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name build_script_build --edition=2021 /opt/conda/conda-bld/fastobo_1714466531501/work/crates/thiserror/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off -C metadata=fb699efc2be7d104 -C extra-filename=-fb699efc2be7d104 --out-dir /opt/conda/conda-bld/fastobo_1714466531501/work/target/release/build/thiserror-fb699efc2be7d104 -C strip=debuginfo -L dependency=/opt/conda/conda-bld/fastobo_1714466531501/work/target/release/deps --cap-lints allow -C linker=/opt/conda/conda-bld/fastobo_1714466531501/_build_env/bin/x86_64-conda-linux-gnu-cc` (exit status: 1)␛[0m
2024-04-30T08:46:36.5576487Z 08:46:25 ␛[32mBIOCONDA INFO␛[0m (OUT)   error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features 'pyo3/extension-module nightly extension-module' --crate-type cdylib --` failed with code 101␛[0m
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>