Fix tqdm needs to be instantiated once
Before using tqdm.tqdm.write, we must have called tqdm.tqdm() once
so that tqdm.tqdm._lock exists, otherwise calling the write will
lead to `AttributeError: type object 'tqdm' has no attribute '_lock'`