viennarna: Skip build for OSX because of compilation problems with naview
`--without-naview` breaks with:
```
2024-03-26T09:58:55.7422620Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR) Undefined symbols for architecture x86_64:␛[0m
2024-03-26T09:58:55.7424070Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR)   "_naview_xy_coordinates", referenced from:␛[0m
2024-03-26T09:58:55.7425890Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR)       _initStacks in libRNA_special_const.a(ugly_bt.o)␛[0m
2024-03-26T09:58:55.7427900Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR) ld: symbol(s) not found for architecture x86_64␛[0m
2024-03-26T09:58:55.7429230Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR) clang-15: error: linker command failed with exit code 1 (use -v to see invocation)␛[0m
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>