[ci skip] Merge PR 19114
Merge PR #19114, commits were: 
 * Skip OSX build

Tried a couple of things, but couldn't figure this out:
```
dyld: lazy symbol binding failed: Symbol not found: _ajAssemdbInit
  Referenced from: /Users/mvandenb/miniconda3/conda-bld/emboss_1576681104992/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libnucleus.6.dylib
  Expected in: flat namespace

dyld: Symbol not found: _ajAssemdbInit
  Referenced from: /Users/mvandenb/miniconda3/conda-bld/emboss_1576681104992/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libnucleus.6.dylib
  Expected in: flat namespace

```
 * Revert "Skip embossupdate hook during make"

This reverts commit 1bf7c77e694a90194b2dbc405cf001d78bc78511.
Doesn't work ...
 * Skip embossupdate hook during make

This fails prior to fixing the linking, which happens later.
 * Update meta.yaml
 * Update meta.yaml
 * Update recipes/emboss/5.0.0/meta.yaml

Co-Authored-By: Nicola Soranzo <nicola.soranzo@gmail.com>
 * Drop emboss from blacklist
 * Update recipes/emboss/5.0.0/meta.yaml

Co-Authored-By: Nicola Soranzo <nicola.soranzo@gmail.com>
 * Use noarch:generic

Seems that's what's needed for binary packages ?
 * Apply suggestions from code review

Co-Authored-By: Nicola Soranzo <nicola.soranzo@gmail.com>
 * Add legacy emboss 5.0 suite