kat - Add cycler dependency
Hello,
I ran `kat hist` in a docker image and ran into issues with the `cycler` package being missing so this PR adds `cycler` as a dependency

```
	    ../lib/include/kat/pyhelper.hpp(159): Throw in function void kat::PyHelper::execute(std::string, int, char**)
	    Dynamic exception type: boost::exception_detail::clone_impl<kat::KatPythonException>
	    std::exception::what: std::exception
	    [kat::KatPythonError*] = Unexpected python error
	    Traceback (most recent call last):
	      File "/usr/local/lib/python3.6/local/kat/plot/spectra_hist.py", line 6, in <module>
	        from misc import *
	      File "/usr/local/lib/python3.6/local/kat/plot/misc.py", line 2, in <module>
	        import matplotlib
	      File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 131, in <module>
	        from matplotlib.rcsetup import defaultParams, validate_backend, cycler
	      File "/usr/local/lib/python3.6/site-packages/matplotlib/rcsetup.py", line 33, in <module>
	        from cycler import Cycler, cycler as ccycler
	    ModuleNotFoundError: No module named 'cycler'
	    
	    During handling of the above exception, another exception occurred:
	    
	    Traceback (most recent call last):
	      File "/usr/local/lib/python3.6/local/kat/plot/spectra_hist.py", line 8, in <module>
	        from kat.plot.misc import *
	      File "/usr/local/lib/python3.6/local/kat/plot/misc.py", line 2, in <module>
	        import matplotlib
	      File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 131, in <module>
	        from matplotlib.rcsetup import defaultParams, validate_backend, cycler
	      File "/usr/local/lib/python3.6/site-packages/matplotlib/rcsetup.py", line 33, in <module>
	        from cycler import Cycler, cycler as ccycler
	    ModuleNotFoundError: No module named 'cycler'
```