Add recipe for smcpp (#52817)
* Add recipe for smcpp

https://github.com/popgenmethods/smcpp

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Try with numpy 1.22

Current error:
```
ValueError: variant config in /home/runner/work/bioconda-recipes/bioconda-recipes/recipes/smcpp/conda_build_config.yaml is ambiguous because it does not fully implement all zipped keys (missing ['python_impl']) or specifies a subspace that is not fully implemented (we did not find ['1.19', '1.20'] from {'python': ['3.9.* *_cpython'], 'numpy': ['1.19', '1.20']} in numpy:['1.22', '1.22', '1.23', '1.26']).
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Fix the git_url

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Try with mpfr 4.1.0

Current error:
```
include/mpreal.h:1064:19: error: no matching function for call to 'mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)'
09:41:32 BIOCONDA INFO (OUT)  1064 |     mpfr_init2(t, mpfr_get_prec(mpfr_srcptr()));
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Use at most matplotlib 3.5.x because in newer versions seaborn styles are removed

```
OSError: 'seaborn-ticks' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)␛[0m
2024-12-16T10:02:46.9233988Z 10:02:36 ␛[32mBIOCONDA INFO␛[0m (OUT) WARNING: Tests failed for smcpp-1.15.4-py39hac1eaed_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken␛[0m
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Add setuptools to host deps

* Do not build for OSX

Error:
```
 (ERR) src/conditioned_sfs.cpp:108:27: error: use of undeclared identifier 'n'␛[0m
12:37:16 ␛[32mBIOCONDA INFO␛[0m (ERR)   108 |         assert(csfs[i](2, n) == 0.);
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

---------

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>