temporarily incactivated snakemake dependency
Creates conflicts with python, which I don't understand since in principle current default python version is 3.8. 
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"python[version='>=2.7,<2.8.0a0']", "python[version='>=3.5.3']"}