update icescreen v1.1.1: minor changes that set the version of the dependency biopython =1.80 instead of >=1.80. The biopython package version 1.81 is incompatible with bcbio-gff version 0.6.9, it throws an ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq'.