Try with numpy 1.22
Current error:
```
ValueError: variant config in /home/runner/work/bioconda-recipes/bioconda-recipes/recipes/smcpp/conda_build_config.yaml is ambiguous because it does not fully implement all zipped keys (missing ['python_impl']) or specifies a subspace that is not fully implemented (we did not find ['1.19', '1.20'] from {'python': ['3.9.* *_cpython'], 'numpy': ['1.19', '1.20']} in numpy:['1.22', '1.22', '1.23', '1.26']).
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>