ViennaRNA: add linux-aarch64 build (#46733)
* ViennaRNA: add linux-aarch64 build

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* viennarna: Disable openmp for MacOS

https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/install.html#macos-x-users

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* viennarna: Disable 'naview' for Mac OS

The build fails with:
```
08:41:36.0304210Z 08:41:14 ␛[32mBIOCONDA INFO␛[0m (OUT) Making all in plotting/naview␛[0m
2024-03-26T08:41:36.0305220Z 08:41:14 ␛[32mBIOCONDA INFO␛[0m (OUT) make[4]: Entering directory '$SRC_DIR/src/ViennaRNA/plotting/naview'␛[0m
2024-03-26T08:41:36.0306020Z 08:41:14 ␛[32mBIOCONDA INFO␛[0m (OUT)   CC       naview.lo␛[0m
2024-03-26T08:41:36.0307370Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR) RNA_wrap.cpp:72350:24: error: use of undeclared identifier 'SWIG_Python_str_AsChar'; did you mean 'SWIG_Python_str_FromChar'?␛[0m
2024-03-26T08:41:36.0308460Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR)     symbolset = strdup(SWIG_Python_str_AsChar(_val));␛[0m
2024-03-26T08:41:36.0309200Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR)                        ^~~~~~~~~~~~~~~~~~~~~~␛[0m
2024-03-26T08:41:36.0310060Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR)                        SWIG_Python_str_FromChar␛[0m
2024-03-26T08:41:36.0311170Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR) RNA_wrap.cpp:857:1: note: 'SWIG_Python_str_FromChar' declared here␛[0m
2024-03-26T08:41:36.0311960Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR) SWIG_Python_str_FromChar(const char *c)␛[0m
2024-03-26T08:41:36.0312640Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR) ^␛[0m
2024-03-26T08:41:36.0313490Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR) RNA_wrap.cpp:72350:47: error: cannot initialize a parameter of type 'const char *' with an lvalue of type 'PyObject *' (aka '_object *')␛[0m
2024-03-26T08:41:36.0315290Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR)     symbolset = strdup(SWIG_Python_str_AsChar(_val));␛[0m
2024-03-26T08:41:36.0316080Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR)                                               ^~~~␛[0m
2024-03-26T08:41:36.0316860Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR) RNA_wrap.cpp:857:38: note: passing argument to parameter 'c' here␛[0m
2024-03-26T08:41:36.0317600Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR) SWIG_Python_str_FromChar(const char *c)␛[0m
2024-03-26T08:41:36.0319140Z 08:41:31 ␛[32mBIOCONDA INFO␛[0m (ERR)                                      ^␛[0m
2024-03-26T08:41:36.0319850Z 08:41:35 ␛[32mBIOCONDA INFO␛[0m (ERR) 2 errors generated.␛[0m
2024-03-26T08:41:36.0320690Z 08:41:35 ␛[32mBIOCONDA INFO␛[0m (ERR) make[3]: *** [Makefile:867: _RNA_la-RNA_wrap.lo] Error 1␛[0m
2024-03-26T08:41:36.0322000Z 08:41:35 ␛[32mBIOCONDA INFO␛[0m (ERR) make[2]: *** [Makefile:670: all-recursive] Error 1␛[0m
2024-03-26T08:41:36.0322800Z 08:41:35 ␛[32mBIOCONDA INFO␛[0m (ERR) make[1]: *** [Makefile:747: all-recursive] Error 1␛[0m
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* viennarna: Skip build for OSX because of compilation problems with naview

`--without-naview` breaks with:
```
2024-03-26T09:58:55.7422620Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR) Undefined symbols for architecture x86_64:␛[0m
2024-03-26T09:58:55.7424070Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR)   "_naview_xy_coordinates", referenced from:␛[0m
2024-03-26T09:58:55.7425890Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR)       _initStacks in libRNA_special_const.a(ugly_bt.o)␛[0m
2024-03-26T09:58:55.7427900Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR) ld: symbol(s) not found for architecture x86_64␛[0m
2024-03-26T09:58:55.7429230Z 09:58:55 ␛[32mBIOCONDA INFO␛[0m (ERR) clang-15: error: linker command failed with exit code 1 (use -v to see invocation)␛[0m
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

---------

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>