zeroc-ice: add build 2 of 3.6.3 to fix openssl issue
openssl in conda has been bumped from 1.0.2 to 1.1.1. Packages such as
zeroc-ice need to be recompiled against the new openssl version,
otherwise there is a linking error:

```
docker run -i -t continuumio/miniconda /bin/bash

conda install -c bioconda python-omero
python -c 'import omero'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python2.7/site-packages/omero/__init__.py", line 17, in <module>
    import Ice
  File "/opt/conda/lib/python2.7/site-packages/Ice.py", line 47, in <module>
    import IcePy
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```