Tabulate 0.9 breaks Snakemake
See details in [snakemake issue 1899](https://github.com/snakemake/snakemake/issues/1899):

tabulate 0.9 reproducibly crashes snakemake with an error:
```text
AttributeError: 'str' object has no attribute 'name'
```