[BULK] Bulk update 191018b (#11419)
* update mzr as a test

* Begin building for R 3.5.1 (#11252)

* Bump everything for R 3.5.1

* Fix most of the linting issues

* Update blacklist

* Revert "Fix most of the linting issues"

This reverts commit a271e50f4b86f4ee76d1148bf78e6617da1b7cc5.

* should_not_use_fn

* More fixes

* Fix incorrect yaml

* Should really fix the linting blacklist stuff

* Fix many recipes

* Fix some linting

* Fix r-wicket

* Update derfinder

* Pin to a given bioconductor release.

* Add missing packages

* Restore identifiers to bioconductor packages

* Restore extra information to R packages

* Update R bulk (#11283)

* fixed incorrect doi of publication (#11175)

* Added recipe for kinSimRiboswitch (#10838)

Added recipe for kinSimRiboswitch, a pipeline for simulating the folding
kinetics of RNA switches.

* update multiqc-bcbio (#11187)

* Add recipe for PopDel (#11181)

* Add recipe for PopDel

* Add clang and clangxx to build config

* update seqbuster (#11190)

* update seqbuster

* fix build

* fix test

* Update pyseer to 1.1.2 (#11172)

* bump sourmash (#11197)

* Update BASIC to v1.4.1 (#11195)

* Update BASIC to v1.4.1

* Trigger circleci

* Fix build number

* Update nf-core-1.2 (#11191)

* Update nf-core-1.2

* Update build script

* Update to InterMine 1.11.0 (#11182)

* Update meta.yaml

* Update meta.yaml

* Update meta.yaml

* Add tinyfasta-0.1.0 (#11177)

* Add tinyfasta

* Update build script

* Fix structure of build section

* Bumping snippy  (#11198)

* Remove older version

* Bump snippy

* VEP: bump major version (#11201)

* VEP: bump major version

* VEP: bumped plugin major version

* VEP: update plugin install

Download and install all plugin modules, instead of just a selection

* Update: PureCN to latest devel (1.11.13); wrapper scripts (#11200)

* Update: PureCN to latest devel (1.11.13); wrapper scripts

PureCN development (https://github.com/lima1/PureCN) has several
improvements over the BioC 3.6 release for handling multiple VCF input
types, and is back compatible with R 3.4.1 so still builds cleanly
with two new dependencies.

Also exposes PureCN wrapper scripts for running from the command line.
Prefixes ambiguous scripts with PureCN_.

* Try pinning to 3.4 to avoid 3.5.1 builds which we don't want yet

* add cassiopee release 1.0.9 (#11168)

* add cassiopee release 1.0.9

* update to conda build 3

* remove old version backup and use sha256 for source

* Bump abeona version to 0.26.0 (#11202)

* Bump abeona version to 0.24.0

* Bump abeona version to 0.26.0

* Update LexMapr to v0.1.2 (#11192)

* Update LexMapr to v0.1.2

* Add rdflib dep

* Update svtyper to 0.7.0 (#11196)

* Update svtyper to 0.7.0

* Add recipe for perl-gtdbtk (#11194)

* Add recipe for perl-gtdbtk

* New recipe for RFMix (#11205)

* New recipe for RFMix
* updated version number information
* updated version number information
* updated version number information

* initial purge_haplotigs commit (#11049)

* initial purge_haplotigs commit
* bioconda revisions, updating test commands to run the pipeline on the test dataset
* rolling back test commands

* Add recipe for fsm-lite (#11209)

* Add recipe for fsm-lite
* Add prefix to make
* Remove v from version string

* Updated reparation_blast to version v.1.0.7 (#11210)

* Update sambamba to 0.6.8 (#11212)

* Bump sambamba to 0.6.8

* It's somewhat annoying that missing_hash is thrown even if uses_git_url is specified.

* Set some environment variables

* The compiled binary is in a different place now

* ldc provides some libraries that are linked against.

* mtbseq: update recipe (#11110)

* changed download location/add test

* remove test

* Confindr (#11217)

* Update confindr to 0.4.2

* Fix typo in specifying version of pysam

* Update Genenotebook to v0.1.4 (#11218)

* genenotebook recipe

* About

* Package name

* License

* sha256sum

* Update build.sh

* Make bin dir

* Change ln to cp

* New symlink strategy

* Build from prebundled tarball

* genenotebook v0.1.2

* version fix

* retry

* fix

* build number

* genenotebook v0.1.3

* restore build procedure

* Fix summary

* updating to 0.1.3 (#11221)

* sartools1.6.6 (#11222)

* Perl bio automatedannotation (#11216)

* Initial recipe for Bio-AutomatedAnnotation

* Change URL

* Run cpanm tests

* Temporarily set HOME

* Use cpan version instead

* Add more depencencies

* Set bioperl version

* unset bioperl version, add bioperl-run

* New release including version in modules

* Remove comments

* build -> host

* Upgrade r-biodb to v1.1.2. (#11213)

* Upgrade r-biodb to v1.1.2.
* Remove old versions of r-biodb.
* Comment out libgfortran.

* PeptideShaker: updated to version 1.16.30 & SearchGUI: updated to version 3.3.5 (#11215)

* PeptideShaker: updated to version 1.16.30

- Bugfix: HOME was still being used when folder with customised reports was specified.
- Bugfix: Made it possible to use the MzidCLI options directly on the PeptideShakerCLI command line.

* SearchGUI: updated to version 3.3.5.

- BUG FIX: Cleanup of the temp path options when used as options for the other command lines.
- FEATURE IMPROVEMENT: Updated Comet to 2018.01 rev. 2.
- LIBRARY UPDATE: Updated utilities to version 4.12.8.

* Update meta.yaml (#11227)

* Svtools 0.4.0 (#11208)

* Remove directories for old svtools versions

* Update svtools to v0.4.0

* Move build number back to 0

* Anvio 52 (#11230)

* Incrementing version to 5.2. Splitting out anvio-minimal package to just install the pip package. The anvio package will install it and all the most likely companion software.

* Remove cgat-scripts from blacklist. (#11228)

* Add new formula: bazam 1.0.1  (#11229)

* Update gatk4 to 4.0.10.0 (#11224)

* Add recipe for gtdbtk 0.1.3 (#11211)

* Add recipe for gtdbtk

* Added initial htstream recipe (#11113)

* HTStream is a fast, quality control pipeline for Hight Throughput Sequencing data. The difference between HTStream and other pipelines is that HTStreams uses a tab delimited fastq format which allows for streaming from application to application. This streaming creates some awesome efficiencies when processing HTS data.

* DeepTools 3.1.3 (#11226)

* PacBio: Update `pbmm2` to version 0.10.0 (#11225)

* fastqc: update to version 0.11.8 (#11214)

* fastqc: update to version 0.11.8

* Update meta.yaml

* Phame (#11223)

* mac recipe and added bioperl

*  changing bill number

* added no osx

* adding new version

* removed separate recipe for mac, dont need it

* now running same recipe for mac and linux

* fixed the way fasttrees version was being parsed

* minor change test

* adding detailed description

* restaging the build number

* new version

* Make sure to use bioperl and perl 5.26

* Updated ngs-bits to version 2018_10 (#11235)

* PacBio: Update `pbsv2` to version 2.0.2 (#11236)

* Update VSEARCH to 2.8.5 (#11239)

* Fix shorah recipe and remove from blacklist. (#11241)

* Fix shorah recipe and remove from blacklist.

* Fix blas variant.

* Remove imports from tests.

* unicycler 0.4.7 (#11240)

* unicycler 0.4.7

* unicycler: Work around ValueError: invalid

Unicycler thinks the terminal has 0 columns and produces this error:
File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/textwrap.py", line 248, in _wrap_chunks
raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -5 (must be > 0)

* Octopus: update to 0.5.1-beta (#11244)

* New: PURPLE SV caller; Update: VarDictJava (1.5.6), PureCN (#11247)

- PURPLE SV and heterogeneity caller for somatic tumor/normal samples.
- VarDictJava -- 1.5.6 release with fixes for SV calling
- PureCN -- add signature dependency and update with fixes for test
  samples.

* Dinucleotide patterns analysis tools v1.0 (#11245)

* Dinucleotide patterns analysis tools v1.0

* Lets try it, it seems to work locally for me.

* Enable SpoTyping_plot.r (#11248)

* rerun again (#11233)

* rerun again

* Update meta.yaml

* Delete build.sh

* Update segway dependency optbuild to 0.2 (#10459)

* Update segway dependency optbuild to 0.2

* Update build and architecture requirements for optbuild 0.2

* Add six as a dependency to the optbuild recipe

* Dinucleotide patterns analysis tools v1. / Add prefix dnp- to the package names (#11249)

* Add prefix dnp- to the package names

* Update build.sh

* Update build.sh

* Bump beast version to 1.10.2 (#11250)

* add maxquant (#11253)

* add mayquant

* relax tests

* PacBio: Update `pbmm2` to version 0.10.1 (#11256)

* PacBio: Update `pbmm2` to version 0.10.1-1 (#11257)

* remove xsv recipe (#11259)

* add blast dependency (#11258)

* Added riborex recipe (#11251)

* Added riborex recipe

* Relaxed version constraints

* Pinned r-core for fdr tools

* fixed the r-base stuff upstream

* Update meta.yaml

* fix graphprot (#11234)

* increase build number

* remove from blacklist

* use cxx instead of c

* move coreutoils to build section

* set additional paths

* patch makefile

* blind try

* update patch

* explicitely copy from src_dir

* update deprecated prefix variable

* Revert "update deprecated prefix variable"

This reverts commit 2559439a76ec60964f6bddd743b27171e8f91b4d.

* update deprecated prefix variable

* try moving to host section

* Bump mash (#11264)

* Add fmlrc (#11265)

* Add fmlrc

* add doi

* PacBio: Update pb-falcon to 0.2.4. (#11266)

* Add kopt recipe (#11269)

* Genomepy 0.5.2 (#11267)

* release 0.5.2 of genomepy

* trigger new build

* remove genomepy from blacklist

* locale for osx

* updated locale test

* PacBio: Update pb-assembly to 0.0.2. Bumped the pinned version for pb-falcon. (#11275)

* Update mmseqs2 recipe to new release 6-f5a1c (#11272)

* Update yacrd to version 0.4.1 (#11273)

* Add scprep (#11270)

* Add scprep

* All of these should not be needed as host dep

* Metawrap preqs2 (#11242)

* fixed issues

* fixed issues

* added tests

* fixed tab

* gemma 0.98 (#11254)

* gemma 0.98

* gemma 0.98

Leave gsl and zlib out of runtime dependencies

* Add DCA recipe (#11274)

* Add DCA recipe

* add noarch and doi

* remove skip

* Fix a bunch of packages that are actually in bioconductor and try to fix bioconductor-rhtslib

* Various fixes for bulk and trigger a rebuild (#11313)

* Various fixes, at least 4 packages (and their dependencies) should still fail (#11320)

* A few fixes, remove a package from the blacklist since it prevents trumicounts from building. (#11336)

* Fix various recipes (#11354)

* Fix various recipes

* Fix more recipes

* Various CRAN package fixes, since they all lack license files (#11372)

* Various CRAN package fixes, since they all lack license files

* Fix the r-dartr recipe

* There is a light at the end of the tunnel (#11381)

* There is a light at the end of the tunnel

* Licenses no longer exist

* [BULK] Fixes for R/Bioconductor packages (#11406)

* Require `r-base >=3.5` for some packages

* Fix various CRAN packages lacking license file

* Add missing libnetcdf requirement to bioconductor-mzr

* Remove r-alakazam (moved to conda-forge)

Fix linting issue:
```
recipes/r-alakazam	in_other_channels	{'exists_in_channels': {'conda-forge'}, 'fix': 'consider deprecating'}	{'conda-forge'}	consider deprecating
```

* [BULK] Many R 3.5 only packages (#11410)

* Update pinning to R>=3.5 and a few runtime dependencies.

* CSAW is R 3.5 only

* Packages using beachmat are 3.5 only

* Packages using bioconductor-singlecellexperiment are R 3.5 only