Update stag (#37104)
* Update stag

If I try to install on my system I have:
```
Package                  Version  Build                   Channel                    Size
─────────────────────────────────────────────────────────────────────────────────────────────
Install:
─────────────────────────────────────────────────────────────────────────────────────────────

+ _libgcc_mutex              0.1  conda_forge             conda-forge/linux-64     Cached
+ _openmp_mutex              4.5  2_gnu                   conda-forge/linux-64     Cached
+ c-ares                  1.11.0  h470a237_1              bioconda/linux-64        Cached
+ ca-certificates      2022.9.14  ha878542_0              conda-forge/linux-64      155kB
+ h5py                    2.10.0  nompi_py36h4510012_106  conda-forge/linux-64        1MB
+ hdf5                    1.10.6  nompi_h6a2412b_1114     conda-forge/linux-64     Cached
+ hmmer                    3.3.2  h87f3376_2              bioconda/linux-64        Cached
+ infernal                 1.1.4  pl5321hec16e2b_1        bioconda/linux-64        Cached
+ joblib                   1.2.0  pyhd8ed1ab_0            conda-forge/noarch        210kB
+ krb5                    1.17.2  h926e7f8_0              conda-forge/linux-64     Cached
+ ld_impl_linux-64        2.36.1  hea4e1c9_2              conda-forge/linux-64     Cached
+ libblas                  3.9.0  16_linux64_openblas     conda-forge/linux-64       13kB
+ libcblas                 3.9.0  16_linux64_openblas     conda-forge/linux-64       13kB
+ libcurl                 7.71.1  hcdd3856_8              conda-forge/linux-64     Cached
+ libedit           3.1.20191231  he28a2e2_2              conda-forge/linux-64     Cached
+ libev                     4.33  h516909a_1              conda-forge/linux-64     Cached
+ libffi                   3.4.2  h7f98852_5              conda-forge/linux-64     Cached
+ libgcc-ng               12.1.0  h8d9b700_16             conda-forge/linux-64     Cached
+ libgfortran-ng          12.1.0  h69a702a_16             conda-forge/linux-64       23kB
+ libgfortran5            12.1.0  hdcd56e2_16             conda-forge/linux-64        2MB
+ libgomp                 12.1.0  h8d9b700_16             conda-forge/linux-64     Cached
+ liblapack                3.9.0  16_linux64_openblas     conda-forge/linux-64       13kB
+ libnghttp2              1.41.0  hab1572f_1              conda-forge/linux-64     Cached
+ libnsl                   2.0.0  h7f98852_0              conda-forge/linux-64     Cached
+ libopenblas             0.3.21  pthreads_h78a6416_3     conda-forge/linux-64       11MB
+ libsqlite               3.39.3  h753d276_0              conda-forge/linux-64      808kB
+ libssh2                 1.10.0  haa6b8db_3              conda-forge/linux-64      239kB
+ libstdcxx-ng            12.1.0  ha89aaad_16             conda-forge/linux-64     Cached
+ libzlib                 1.2.12  h166bdaf_3              conda-forge/linux-64       66kB
+ ncurses                    6.3  h27087fc_1              conda-forge/linux-64     Cached
+ numpy                   1.19.5  py36hfc0c790_2          conda-forge/linux-64     Cached
+ openssl                 1.1.1q  h166bdaf_0              conda-forge/linux-64     Cached
+ pandas                   1.1.5  py36h284efc9_0          conda-forge/linux-64     Cached
+ perl                    5.32.1  2_h7f98852_perl5        conda-forge/linux-64     Cached
+ pip                     21.3.1  pyhd8ed1ab_0            conda-forge/noarch       Cached
+ prodigal                 2.6.3  hec16e2b_4              bioconda/linux-64        Cached
+ python                  3.6.15  hb7a2778_0_cpython      conda-forge/linux-64     Cached
```

Where python 3.6 causes the following error:
```
File "/nfs/nas22/fs2202/biol_micro_sunagawa/Projects/STU/SSUNDAR_STU/scratch/raw/temp_conda/envs/stag_test/bin/stag", line 33, in <module>
  sys.exit(load_entry_point('stag===-0.8.2-', 'console_scripts', 'stag')())
File "/nfs/nas22/fs2202/biol_micro_sunagawa/Projects/STU/SSUNDAR_STU/scratch/raw/temp_conda/envs/stag_test/lib/python3.6/site-packages/stag/__main__.py", line 422, in main
  save_ali_to_file=args.intermediate_al, min_perc_state=args.min_perc_state)
File "/nfs/nas22/fs2202/biol_micro_sunagawa/Projects/STU/SSUNDAR_STU/scratch/raw/temp_conda/envs/stag_test/lib/python3.6/site-packages/stag/classify.py", line 135, in classify
  db = load_db(database, protein_fasta_input=protein_fasta_input, aligned_sequences=aligned_sequences)
File "/nfs/nas22/fs2202/biol_micro_sunagawa/Projects/STU/SSUNDAR_STU/scratch/raw/temp_conda/envs/stag_test/lib/python3.6/site-packages/stag/databases.py", line 38, in load_db
  params_out = open(os.path.join(dir_output, "parameters.tsv"), "w") if dir_output else contextlib.nullcontext()
AttributeError: module 'contextlib' has no attribute 'nullcontext'
Error (1.385s)
```

Which seems to be related to python<3.7 (see https://stackoverflow.com/questions/69520829/openai-gym-attributeerror-module-contextlib-has-no-attribute-nullcontext)

Hence I require that also during running I have `python>=3.7`

* Update meta.yaml