perl-bio-samtools: bump samtools minor version and add linux-aarch64 and osx-arm64 (#52576)
* Bump build number, will this bump a rebuild on linux-aarch64?

* update legacy builds for samtools to support linux-aarch64 and osx-arm64

* don't build for osx - fails with

error: /opt/mambaforge/envs/bioconda/conda-bld/samtools_1733249731471/_build_env/bin/x86_64-apple-darwin13.4.0-install_name_tool: changing install names or rpaths can't be redone for: /opt/mambaforge/envs/bioconda/conda-bld/samtools_1733249731471/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include/bam/misc/ace2sam (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)

* Add make -j

* Add osx-arm64 and linux-aarch64; bump build; bump max samtools supported (1.43 changelog shows up to samtools-0.1.19 is supported)

* fix jinja usage!

* list osx-arm64 dependencies

* change to add bam file if in include/bam - per 0.1.19

* select functional version to work against

* Add -fPIC to CFLAGS

* Bump build number - for -fPIC libbam.a