mpa-portable: add fonts and fix permissions
Try to fix:

```
java.io.FileNotFoundException: /usr/local/share/mpa-portable-1.4.1-2/built/X!Tandem/linux/linux_64bit/taxonomy.xml (Permission denied)
```

for running in a docker container by using chmod.

Without fonts-conda-ecosystem and openjdk 11 we get

```
|  Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
|  at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
|  at java.base/java.security.AccessController.doPrivileged(Native Method)
|  at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
|  at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:247)
|  at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
|  at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1231)
|  at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1646)
|  at java.desktop/javax.swing.text.PlainView.calculateLongestLine(PlainView.java:783)
|  at java.desktop/javax.swing.text.PlainView.updateMetrics(PlainView.java:332)
|  at java.desktop/javax.swing.text.PlainView.updateDamage(PlainView.java:670)
|  at java.desktop/javax.swing.text.PlainView.insertUpdate(PlainView.java:591)
|  at java.desktop/javax.swing.text.FieldView.insertUpdate(FieldView.java:294)
|  at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(BasicTextUI.java:1709)
|  at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(BasicTextUI.java:1968)
|  at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
|  at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
|  at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
|  at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
|  at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:675)
|  at java.desktop/javax.swing.text.JTextComponent.setText(JTextComponent.java:1729)
|  at java.desktop/javax.swing.JFormattedTextField$AbstractFormatter.install(JFormattedTextField.java:957)
|  at java.desktop/javax.swing.text.DefaultFormatter.install(DefaultFormatter.java:125)
|  at java.desktop/javax.swing.text.InternationalFormatter.install(InternationalFormatter.java:286)
|  at java.desktop/javax.swing.JFormattedTextField.setFormatter(JFormattedTextField.java:474)
|  at java.desktop/javax.swing.JFormattedTextField.setValue(JFormattedTextField.java:797)
|  at java.desktop/javax.swing.JFormattedTextField.setValue(JFormattedTextField.java:511)
|  at java.desktop/javax.swing.JSpinner$DefaultEditor.<init>(JSpinner.java:625)
|  at java.desktop/javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1230)
|  at java.desktop/javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1206)
|  at java.desktop/javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1181)
|  at java.desktop/javax.swing.JSpinner.createEditor(JSpinner.java:252)
|  at java.desktop/javax.swing.JSpinner.<init>(JSpinner.java:157)
|  at de.mpa.client.settings.PostProcessingParameters$MetaProteinParameters.createPanel(PostProcessingParameters.java:172)
|  at de.mpa.client.settings.PostProcessingParameters$MetaProteinParameters.createLeftComponent(PostProcessingParameters.java:143)
|  at de.mpa.client.settings.PostProcessingParameters.initDefaults(PostProcessingParameters.java:61)
|  at de.mpa.client.settings.ParameterMap.<init>(ParameterMap.java:18)
|  at de.mpa.client.settings.PostProcessingParameters.<init>(PostProcessingParameters.java:39)
|  at de.mpa.client.Client.<init>(Client.java:49)
|  at de.mpa.client.Client.init(Client.java:108)
|  at de.mpa.cli.CmdLineInterface.call(CmdLineInterface.java:110)
|  at de.mpa.cli.CmdLineInterface.<init>(CmdLineInterface.java:76)
|  at de.mpa.cli.CmdLineInterface.main(CmdLineInterface.java:294)
|  Caused by: java.lang.reflect.InvocationTargetException
|  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
|  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
|  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
|  at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
|  at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
|  ... 41 more
|  Caused by: java.lang.NullPointerException
|  at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
|  at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
|  at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
|  at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
|  at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:367)
|  at java.base/java.security.AccessController.doPrivileged(Native Method)
|  at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:312)
|  at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
|  at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
|  ... 46 more
```

because the openjdk recipe up to version 10 did not require fontconfig.