[ci skip] Merge PR 39601
Merge PR #39601, commits were: 
 * also bump mitos1

and doc fix
 * bump
 * pin libtiff
 * just try to pin to conda forge
 * bump
 * try to pin pillow

because reportlab fails with

```
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
```