[ci skip] Merge PR 21211
Merge PR #21211, commits were: 
 * deepvariant: 0.10.0: fix zipfile issue, finalize deps

- Fixes deepvariant issue with zipfile synlink references causing:
  ```
  TypeError: allele_count_linear_candidates_from_allele_counter() argument counter is
    not valid for ::learning::genomics::deepvariant::AlleleCounter
    (deepvariant.python.allelecounter.AlleleCounter instance given):
    expecting deepvariant.python.allelecounter.AlleleCounter instance, got
    deepvariant.python.allelecounter.AlleleCounter instance
  ```
  By adding `--symlinks` when recreating zipfile, thanks to reading
  through deepvariant build patch (https://github.com/google/deepvariant/issues/199#issuecomment-570115804)
  Fixes bcbio/bcbio-nextgen#3048

- Includes missing dependencies in new version: altair and absl.
  Includes custom Google tf-slim which duplicates other tf-slims and is
  in the process of being merged into a single package.
  Fixes bcbio/bcbio-nextgen#3150

- Bumps model version to include correct version