Recipe for the bioconductor package roar
Right now R version is blocked to avoid:
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - bioconductor-summarizedexperiment -> bioconductor-biobase -> bioconductor-biocgenerics >=0.3.2 -> r 3.2.2* -> r-base 3.2.2
  - bioconductor-summarizedexperiment -> bioconductor-biobase -> bioconductor-biocgenerics >=0.3.2 -> r 3.2.2* -> r-recommended 3.2.2
  - r 3.3.2*