bump qiime
for join_paired_ends.py the current biocontainer gives me

```
Traceback (most recent call last):
  File "/usr/local/bin/join_paired_ends.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.1', 'join_paired_ends.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/join_paired_ends.py", line 11, in <module>
    from qiime.join_paired_ends import (join_method_names,
  File "/usr/local/lib/python2.7/site-packages/qiime/join_paired_ends.py", line 15, in <module>
    from qiime.util import qiime_open
  File "/usr/local/lib/python2.7/site-packages/qiime/util.py", line 41, in <module>
    from biom.util import compute_counts_per_sample_stats, biom_open, HAVE_H5PY
  File "/usr/local/lib/python2.7/site-packages/biom_format-2.1.5-py2.7-linux-x86_64.egg/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/usr/local/lib/python2.7/site-packages/biom_format-2.1.5-py2.7-linux-x86_64.egg/biom/table.py", line 190, in <module>
    from biom.util import (get_biom_format_version_string,
  File "/usr/local/lib/python2.7/site-packages/biom_format-2.1.5-py2.7-linux-x86_64.egg/biom/util.py", line 24, in <module>
    import h5py
  File "/usr/local/lib/python2.7/site-packages/h5py/__init__.py", line 60, in <module>
    from .tests import run_tests
  File "/usr/local/lib/python2.7/site-packages/h5py/tests/__init__.py", line 15, in <module>
    from . import old, hl
  File "/usr/local/lib/python2.7/site-packages/h5py/tests/old/__init__.py", line 4, in <module>
    from . import ( test_attrs,
  File "/usr/local/lib/python2.7/site-packages/h5py/tests/old/test_group.py", line 41, in <module>
    fsencode(u"α")
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/compat.py", line 68, in fsencode
    return filename.encode(encoding, errors)
  File "/usr/local/lib/python2.7/site-packages/future/utils/surrogateescape.py", line 59, in surrogateescape_handler
    decoded = replace_surrogate_encode(mystring)
  File "/usr/local/lib/python2.7/site-packages/future/utils/surrogateescape.py", line 86, in replace_surrogate_encode
    raise exc
NameError: global name 'exc' is not defined
```

seems to be a problem with future 0.16 that is solved in later versions.