Cnv facets (#13073)
* First draft

* Restrict to linux

* Add snp-pileup dependency

* Do not use setup script

If some dependency is missing, edit meta.yaml or explicitly put
dependecies build.sh

* Install without setup.sh

* Fix R command

* Move test to meta.yaml

* Fix yaml line

* Test moved to build script to resolve #38177 (upload-linux)

* Install jsonlite in build script

After installation, argparse fails as it cannot find jsonlite (?!) so we
install jsonlite explicitly.

Version bumped so the version string from cnv_facets.R -v agrees with the
release version

* Try moving jsonlite from build to meta

This to try to resolve the error occurring *after* downloading
cnv_facets:

    cnv_facets.R -h
    Error: package or namespace load failed for ‘argparse’ in
    loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
    there is no package called ‘jsonlite’
    Execution halted

* Bump buld number

* Recipe for version 0.12.0

* Update to v0.12.1