pb-falon: htslib=1.7
Attempting to solve this problem:
```
% conda install pb-falcon=0.2.1
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in
conflict:
  - pb-falcon=0.2.1
  - pbalign -> pbbam[version='>=0.18.0'] -> htslib=1.7
```