another try
ValueError: Didn't find subpackage version info for 'openms-meta', which is used in a pin_subpackage expression.  Is it actually a subpackage?  If not, you want pin_compatible instead.