mira 4.9.5 and 4.9.6 (developement series) (#5455)
* MIRA 4.9.5 (development branch)

* MIRA 4.9.6 (development branch), Linux + macOS

* fix typo

* some cleanups

* cleanups

* Remove comment lines which apparently broke linting

* MIRA 4.9.6 has no scripts folder

* MIRA 4.9.6 Mac OS X binaries fail our tests.

Error: Could not find libstdc++.6.dylib

(Also seen with the MIRA 4.0.2 recipe)