fix: nanosim scikit-learn dependency fixed to pretrained-model version (#53528)
* fix: nanosim scikit-learn dependency fixed to pretrained-model version

* chore: update further dependencies according to the requirements.txt

* Revert "chore: update further dependencies according to the requirements.txt"

This reverts commit e400bd9766bd3f1d85e3a7c08c0cb3e0b696b303.

* fix: maximum constraint for numpy, to avoid `AttributeError: module 'numpy' has no attribute 'float'`

see: https://stackoverflow.com/a/74861894