sipros limit mono version (#55643)
* sipros limit mono version

otherwise the Rexport executable fails with

```
System.ArgumentOutOfRangeException: Instrument index not available for requested device
```

https://github.com/compomics/ThermoRawFileParser/issues/106

* bump

* also copy ClusterSip.py and symlink shell script

* Revert "also copy ClusterSip.py and symlink shell script"

This reverts commit 35094ff3e0c943b8bf3a67476dd28ec12072e5b7.